version: "3.9"

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: storage-ipfs
    ports:
      - "4001:4001"   # p2p
      - "5001:5001"   # API
      - "8081:8080"   # Gateway
    volumes:
      - ipfs-data:/data/ipfs
    environment:
      IPFS_PROFILE: server
    command: ["daemon", "--migrate=true"]

volumes:
  ipfs-data: